release-argus/Website

content/en/docs/Examples/services.md

Create a collection of sample configurations to monitor different services

add Service examples

---

content/en/docs/Examples/services.md

Add deployed_version for Mailcow, requires Mailcow version 2022-05
Add Regex to deployed_version for Rancher to fix version

Add Mailcow deployed_version + Rancher fix

---

content/en/docs/Config/gotify.md

Fixes typo in Gotify config docs

Fix typo in Gotify config docs

---

content/en/docs/Examples/services.md

Add example Service configuration for [goharbor/harbor](https://github.com/goharbor/harbor)

Add goharbor/harbor

---

content/en/docs/Examples/services.md

Add Service example for [matrix-org/synapse](https://github.com/matrix-org/synapse) and [vector-im/element-web](https://github.com/vector-im/element-web)

Add Matrix Stack

---

content/en/docs/Examples/services.md

- Add `deployed_version` to `dani-garcia/vaultwarden`
- Remove second Codeblock end by `healthchecks/healthchecks`

Add deployed_version to dani-garcia/vaultwarden

---

content/en/docs/Config/notify.md

https://github.com/release-argus/Argus/pull/77

show `mattermost.params.icon`

---

content/en/docs/Config/webhook.md

Add docs for Webhook type `gitlab`.
https://github.com/release-argus/Argus/pull/95

Add Webhook type GitLab

---

content/en/docs/Config/settings.md
content/en/docs/Getting started/_index.md
content/en/docs/Getting started/faq.md

Restriction on re-sends:
https://github.com/release-argus/Argus/pull/110
SQLite DB:
https://github.com/release-argus/Argus/pull/113

0.8.0 changes

---

content/en/docs/Config/service.md
content/en/docs/Config/settings.md

Update docs for new `config.yml` styling in
https://github.com/release-argus/Argus/pull/135
and basic auth from
https://github.com/release-argus/Argus/pull/140

`0.9.0` config changes

---

content/en/docs/Config/service.md

[b575030efc59ac62ff85d0fca753cbc1ec788a08](https://github.com/release-argus/Argus/commit/b575030efc59ac62ff85d0fca753cbc1ec788a08)

`require.docker` docs

---

content/en/docs/Config/service.md

[799c9fc1986af1da8ae537a2837a5735f9d94293](https://github.com/release-argus/Argus/commit/799c9fc1986af1da8ae537a2837a5735f9d94293)

`require.command` docs

---

config.toml
content/en/docs/Getting started/_index.md

https://github.com/release-argus/Argus/issues/158

Docker healthcheck example

---

content/en/docs/Examples/services.md

I'm back for yet another service!
Example response: 
```json
{
"version": "1.2.1",
"commitTag": "$GITHUB_SHA",
"updateAvailable": false,
"commitsBehind": 0,
"restartRequired": false
}
```

Add `Fallenbagel/jellyseerr` service example

---

content/en/docs/Examples/services.md

Add deployed_version for element-web.

Add deployed_version to vector-im/element-web

---

config.toml
content/en/_index.html
content/en/about/_index.html
content/en/docs/Config/notify.md
content/en/docs/Config/service.md
content/en/docs/Config/settings.md
content/en/docs/Config/webhook.md
content/en/docs/Getting started/faq.md
go.mod
go.sum
package-lock.json
package.json

docs(0.16.0): some env vars in config

---

content/en/docs/Help/regex.md

Hello, I have replaced a resource  (regoio / dead link) by another regex testers in regex.md

Replaced dead link resource (regoio) in regex.md

---

content/en/docs/Examples/services.md

Takes advantage of the 0.18.0 HTTP methods.

Added EMQX example

---

content/en/docs/Examples/services.md

here are examples for [traccar/traccar](https://github.com/traccar/traccar) and [firefly-iii/firefly-iii](https://github.com/firefly-iii/firefly-iii).

Add traccar & firefly-iii

---

content/en/docs/Examples/services.md

Added examples with `deployed_version` of:
- Audiobookshelf
- Flaresolverr
- FreshRSS
- Glance
- Hoarder
- Lidarr
- OliveTin
- Plex Media Server
- Readarr
- Overseerr
- Tautulli
- Memos
I'll appreciate a proofread just to make sure everything looks fine just in case I made any mistakes. Hopefully everything is fine!

Added more examples of services

---

config.toml
content/en/docs/Config/_index.md
content/en/docs/Config/notify.md
content/en/docs/Config/service.md
go.mod
go.sum

bump docsy from 0.9.1 to 0.10.0

---

content/en/docs/Config/service.md

'manual' type and 'target_header' param

0.22.0: `deployed_version` updates
