- content/en/docs/Examples/services.md
Added `/api/v1/version` with https://github.com/hymenaios-io/Hymenaios/pull/19. Just waiting on a build before we merge this
> Add `hymenaios-io/hymenaios` Service example

- content/en/docs/Examples/services.md
also revert Rancher `deployed_version` regex to `v([0-9.]+)`
FYI @larsl-net. Reverting regex as it was only suggested because I misread the changes and thought it was for Matomo where the tag doesn't have the `v`. Removing this `accept` header as mine works without it (can be seen on the demo page. Those *.example.io's are going to my own services, I've just setup DNS on the demo server to resolve *.example.io to my services in order to not advertise their addresses)
> Remove superfluous `accept` header from mailcow

- content/en/docs/Examples/services.md
Add deployed_verion to `synapse` and `awx`.
Update the deployed_version for `netbox` from regex to an API call.
The `awx` integration is untested (based on the [docs](https://docs.ansible.com/ansible-tower/latest/html/towerapi/api_ref.html#/System_Configuration/System_Configuration_ping_list)) as I am not running `awx`. 
Can anyone test it with a real instance?
Added [opnsene/core](https://github.com/opnsense/core)
> Add Deployed versions + New Services

- content/en/docs/Examples/services.md
Add `semantic_versioning: false` to `healthchecks/healthchecks` else the newest Release v2.1 is not detected as latest version.
> Fix healthchecks/healthchecks

- content/en/docs/Examples/services.md
Changed "josn" to "json" i wiki.js example
> Fixed wiki.js typo

- content/en/docs/Examples/services.md
Add argoproh/argo-cd service example.
Service has a version endpoint that returns a JSON object like so:
```
{"Version":"v2.4.14+029be59"}
```
Regex: `v([0-9.]+)$` has picked up the versions just fine so far in the past 6 months.
> Add `argoproj/argo-cd` service example

- content/en/docs/Examples/services.md
Swagger docs (For Radarr/Radarr which has very similar API): https://radarr.video/docs/api/#/System/get_api_v3_system_status
```json
{
"version": "3.0.9.1549",
"buildTime": "2022-08-06T15:55:48Z",
"isDebug": false,
"isProduction": true,
"isAdmin": false,
"isUserInteractive": false,
"startupPath": "/app/sonarr/bin",
"appData": "/config",
"osName": "ubuntu",
"osVersion": "20.04",
"isMonoRuntime": true,
"isMono": true,
"isLinux": true,
"isOsx": false,
"isWindows": false,
"branch": "main",
"authentication": "none",
"sqliteVersion": "3.31.1",
"urlBase": "",
"runtimeVersion": "6.12.0.182",
"runtimeName": "mono"
}
```
- Sonarr/Sonarr does not maintain a CHANGELOG as explained in the [Github issue](https://github.com/Sonarr/Sonarr/issues/2059). The `web_url` instead directs to …
> Add `Sonarr/Sonarr` service example

- content/en/docs/Examples/services.md
Swagger docs: https://api.jellyfin.org/#tag/System/operation/GetPublicSystemInfo
```json
{
"LocalAddress": "https://10.32.1.130:8920",
"ServerName": "jellyfin-a3c1f87ea-lkjei",
"Version": "10.8.5",
"ProductName": "Jellyfin Server",
"OperatingSystem": "Linux",
"Id": "c88213349eec233df62b33706b077e55",
"StartupWizardCompleted": true
}
```
Found that version information is actually available on a public, unauthenticated API endpoint. No API key is necessary.
Ref: Issue #26
> Add `jellyfin/jellyfin` service example

- content/en/docs/Examples/services.md
Swagger docs: https://radarr.video/docs/api/#/System/get_api_v3_system_status
```json
{
"appName": "Radarr",
"instanceName": "Radarr",
"version": "4.2.4.6635",
"buildTime": "2022-09-25T02:16:02Z",
"isDebug": false,
"isProduction": true,
"isAdmin": false,
"isUserInteractive": true,
"startupPath": "/app/radarr/bin",
"appData": "/config",
"osName": "LinuxMusl",
"isNetCore": true,
"isLinux": true,
"isOsx": false,
"isWindows": false,
"isDocker": false,
"mode": "console",
"branch": "master",
"authentication": "none",
"databaseType": "sqLite",
"databaseVersion": "3.36.0",
"migrationVersion": 214,
"urlBase": "",
"runtimeVersion": "6.0.8",
"runtimeName": "netCore",
"startTime": "2022-10-07T19:46:59Z",
"packageVersion": "4.2.4.6635-ls153",
"packageAuthor": …
```
> Add `Radarr/Radarr` service example

- content/en/docs/Examples/services.md
Swagger docs: https://prowlarr.com/docs/api/#/System/get_api_v1_system_status
```json
{
"appName": "Prowlarr",
"instanceName": "Prowlarr",
"version": "0.4.6.1969",
"buildTime": "2022-09-13T04:02:55Z",
"isDebug": false,
"isProduction": true,
"isAdmin": false,
"isUserInteractive": true,
"startupPath": "/app/prowlarr/bin",
"appData": "/config",
"osName": "LinuxMusl",
"isNetCore": true,
"isMono": false,
"isLinux": true,
"isOsx": false,
"isWindows": false,
"isDocker": false,
"mode": "console",
"branch": "develop",
"authentication": "none",
"databaseType": "sqLite",
"databaseVersion": "3.36.0",
"migrationVersion": 21,
"urlBase": "",
"runtimeVersion": "6.0.6",
"runtimeName": "netCore",
"startTime": "2022-10-28T18:16:44Z",
"packageVersion": "0.4.6.1969-ls69",
"packageAuthor": …
```
> Add `Prowlarr/Prowlarr` service example

- content/en/docs/Examples/services.md
No swagger docs found but I grabbed the request/response from the developer console in Chrome
```json
{
"data": {
"bazarr_config_directory": "/config", 
"bazarr_directory": "/app/bazarr/bin", 
"bazarr_version": "1.1.1", 
"operating_system": "Linux-5.15.74-rockchip64-aarch64-with", 
"package_version": "v1.1.1-ls167 by [linuxserver.io](https://linuxserver.io)", 
"python_version": "3.9.5", 
"radarr_version": "4.2.4.6635", 
"sonarr_version": "3.0.9.1549", 
"start_time": 1666981051.104633, 
"timezone": "Asia/Singapore"
}
}
```
> Add `morpheus65535/bazarr` service example

- content/en/docs/Examples/services.md
Image URL changed in https://github.com/home-assistant/core/commit/80b357262795a57dc267a313064266fd2682ca74
> Fix home-assistant/core image URL

- content/en/docs/Examples/services.md
Grafana no longer provides release notes in the documentation since v9.2.
https://grafana.com/docs/grafana/latest/release-notes/
> fix: Grafana release notes

- content/en/docs/Getting started/_index.md
Only for `argus.db` for now, but doing this rather than the file bind mount prevents an anonymous bind mount for the volume. (Volume as we'd rather keep the db when updating)
#48
> Docker: Use folder mount for storage volume

- content/en/docs/Getting started/_index.md
`/home/argus/argus` can't be the binary if `/home/argus/argus/config.yml` is the config
> Fix systemd paths

- content/en/docs/Examples/services.md
The matrix server synapse has been moved from matrix-org to the element-hq org on GitHub.
> fix: Migrate to synapse to element-hq

- content/en/docs/Help/_index.md
- content/en/docs/Monitor/_index.md
- content/en/docs/Monitor/prometheus.md
Resolves: https://github.com/release-argus/Website/issues/83
First of all, thank you for this fantastic project!
We started using this on production but couldn't find any documents on monitoring Argus.
I glanced at the source code and realized that it exports Prometheus metrics. Amazing!
If this is documented, it would be great. 
Thank you in advance!
> Add monitor documentation

- content/en/docs/Examples/services.md
Immich has deprecated and removed the API endpoint, which was used to get the current deployed version.
> Immich use new API endpoint

- content/en/docs/Examples/services.md
Compatible as of 2.43.0 as part of https://github.com/ellite/Wallos/commit/ff13fcb6547ec4a9c972a2c0f0b6f42d69620f8b
> Added Wallos service example.

- content/en/docs/Legal/cookies.md
- content/en/docs/Legal/disclaimer.md
- content/en/docs/Legal/terms-and-conditions.md
- go.mod
- go.sum
- `YYYY-MM-DD` instead of `YYYY-M-D`
- bump FortAwesome/Font-Awesome from v0.0.0-20240402185447-c0f460dca7f7 to v0.0.0-20240716171331-37eff7fa00de
- bump divinerites/plausible-hugo from v1.20.0 to v1.21.1
- bump google/docsy from v0.10.0 to v0.11.0
> Fix front-matter dates and update to latest releases

- content/en/docs/Config/notify.md
Just a small update to indicate how to login to ntfy with access token. Also corrected a link to shoutrrr.
> notify(ntfy): add `password: access_token` info
